-- Baseline schema (H2) as of the Flyway introduction.
-- Existing databases without flyway_schema_history are registered as version 1 (baseline-on-migrate)
-- and never run this script; it only creates new databases.
-- Generated from the JPA mappings. command_log.status keeps the production definition from
-- db/manual/command-log-status.sql (VARCHAR with DEFAULT 'UNKNOWN') so an older JAR can still insert rows.

create table users (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    refresh_token varchar(512),
    email varchar(255) not null unique,
    github_access_token varchar(255),
    name varchar(255) not null,
    provider_id varchar(255),
    role enum ('ADMIN','USER'),
    primary key (id)
);

create table cli_access_tokens (
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    id bigint generated by default as identity,
    last_used_at timestamp(6),
    revoked_at timestamp(6),
    updated_at timestamp(6) not null,
    user_id bigint not null,
    token_prefix varchar(12) not null,
    token_hash varchar(64) not null unique,
    name varchar(100) not null,
    primary key (id)
);

create table cli_auth_sessions (
    approved_at timestamp(6),
    approved_by_user_id bigint,
    consumed_at timestamp(6),
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    rejected_at timestamp(6),
    updated_at timestamp(6) not null,
    user_code varchar(16) not null unique,
    cli_version varchar(40) not null,
    id varchar(64) not null,
    platform varchar(80) not null,
    client_name varchar(120) not null,
    hostname varchar(120) not null,
    status enum ('APPROVED','CONSUMED','EXPIRED','PENDING','REJECTED') not null,
    primary key (id)
);

create table conversation_session (
    active boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    last_active_at timestamp(6),
    updated_at timestamp(6) not null,
    user_id bigint not null,
    session_token varchar(255) not null unique,
    primary key (id)
);

create table command_log (
    confirmed boolean not null,
    is_executed boolean not null,
    requires_confirmation boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    session_id bigint,
    updated_at timestamp(6) not null,
    user_id bigint,
    ai_response TEXT,
    error_message varchar(255),
    execution_result TEXT,
    intent_args TEXT,
    raw_command varchar(255) not null,
    interpreted_intent VARCHAR(50),
    risk_level enum ('HIGH','LOW','MEDIUM'),
    status varchar(20) default 'UNKNOWN' not null,
    primary key (id)
);

create table repositories (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    user_id bigint,
    external_build_project_id varchar(255),
    git_url varchar(255) not null,
    owner varchar(255) not null,
    repo_name varchar(255) not null,
    cloud_vendor enum ('AWS','NCP','ON_PREMISE') not null,
    primary key (id)
);

create table deployment_configs (
    container_port integer not null,
    max_replicas integer not null,
    min_replicas integer not null,
    node_port integer,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    repository_id bigint unique,
    updated_at timestamp(6) not null,
    env_from_config_maps TEXT,
    env_from_secrets TEXT,
    env_vars TEXT,
    domain_url varchar(255) not null,
    image_pull_secret_name varchar(255),
    image_uri_template varchar(255),
    build_strategy enum ('GITHUB_ACTIONS_GHCR','KANIKO','PREBUILT_IMAGE'),
    service_type enum ('CLUSTER_IP','NODE_PORT'),
    primary key (id),
    constraint uk_deployment_configs_domain_url unique (domain_url)
);

create table deployments (
    created_at timestamp(6) not null,
    finished_at timestamp(6),
    id bigint generated by default as identity,
    repository_id bigint,
    started_at timestamp(6),
    updated_at timestamp(6) not null,
    branch_name varchar(255) not null,
    commit_hash varchar(255) not null,
    external_build_id varchar(255),
    fail_reason TEXT,
    image_uri varchar(255),
    storage_object_key varchar(255),
    status enum ('BUILDING','CANCELED','DEPLOYING','FAILED','PENDING','SUCCESS','UPLOADING_SOURCE') not null,
    primary key (id)
);

create table scaling_history (
    new_replicas integer not null,
    previous_replicas integer not null,
    created_at timestamp(6) not null,
    deployment_id bigint not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    triggered_by varchar(20) not null,
    primary key (id)
);

alter table cli_access_tokens add constraint FK3tqqp77eo0684rfmme6p0uq2q foreign key (user_id) references users;
alter table command_log add constraint FK7wwmd1nxnoyn9glyaucorib41 foreign key (session_id) references conversation_session;
alter table command_log add constraint FKjs107ycnfyoxv0qmwchhbotjc foreign key (user_id) references users;
alter table conversation_session add constraint FKnoaewk6mjq60sshi4w5t3dq68 foreign key (user_id) references users;
alter table deployment_configs add constraint FK6qvmhc4clohes8431h631etec foreign key (repository_id) references repositories;
alter table deployments add constraint FKa2mveglpcjpdeir0hsamifml7 foreign key (repository_id) references repositories;
alter table repositories add constraint FK7ufrpdgoll6ftsk8i4vdio8r9 foreign key (user_id) references users;
alter table scaling_history add constraint FKb9s81k5usdm7yhutddjw8aobr foreign key (deployment_id) references deployments;
